### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by randoom15** [pytransitions/transitions-gui#10]
Tried the sample code on my win10 pc, with tornado installed with pip

```
  File "C:\Users\nicol\AppData\Local\Programs\Python\Python38-32\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
```

**Comment by aleneum** [comment]
Hi @randoom15,

this is probably related to this issue: https://github.com/tornadoweb/tornado/issues/2751

**Comment by randoom15** [comment]
That might be it, will test later :)

**Comment by aleneum** [comment]
I am closing this since there hasnt been new comments in quite a while. If this issue still persists and is caused by `transitions-gui`. feel free to comment anyway. I will open the issue again if needed.
