### ISSUE TITLE
Internal transitions not supported

### ISSUE THREAD

**Issue by ftronel** [pytransitions/transitions-gui#9]
If you add an internal transition (with None as destination state as explained by https://github.com/pytransitions/transitions#internal-transitions) the Javascript code will not be able to render the automaton since the destination state is not found. Chrome console gives the following backtrace:

> ERROR:  Error: Can not create edge `2ab32791-eac0-4556-87d2-c8507e8cc50b` with unspecified target
>     at le (main.js:formatted:1192)
>     at Zi.$i.restore (main.js:formatted:7754)
>     at new Zi (main.js:formatted:7552)
>     at Mo.add (main.js:formatted:8000)
>     at main.js:formatted:11274
>     at main.js:formatted:11287
>     at main.js:formatted:11265
>     at new Mo (main.js:formatted:11266)
>     at qs (main.js:formatted:18948)
>     at main.js:formatted:28089

**Comment by aleneum** [comment]
Hi @ftronel,

I added handling of internal transitions/edges and also added some markup for conditions and enter/exit callbacks. I hope that fixes your issue.

**Comment by ftronel** [comment]
Hi   @aleneum,

Many thanks for fixing quickly this issue. It works very well. I'm using your library for a lecture on network protocols in Python, where we design a small protocol using automata to describe the behaviour of a server and its clients. Messages are encoded using ASN.1. I need to visualize both automata (server and client side) in live. Until now, I was using the GraphMachine with an export in PNG using pygraphviz. However, this library is poorly packaged under Windows (and my students are almost all using MS Windows). So, being able to visualize automaton in a Web browser is far more easier for my students.

**Comment by aleneum** [comment]
Great! Always nice to see lecturers going the extra mile to make their topic more comprehensible! If you or your students have some feedback, let me know :).
